### ISSUE TITLE
front page doesn't validate

### ISSUE THREAD

**Issue by fuzzie** [scummvm/scummvm-web#51] opened 2016-04-08 08:55 UTC
We have a link to the W3C HTML validator on the front page, but it doesn't validate (due to the paypal link and an extra end tag). I assume @salty-horse will go fix this now.

**Comment by sev-** [comment] 2016-04-08 09:01
Yes, I saw that yesterday. Regarding the paypal link, this is really interesting, but the validator complains that in the following tag:

`<input type="image" src="/images/ppdonate.png" width="88" height="35" border="0" name="submit" alt="Support This Project">`

width, height and border attributes are not allowed. However, they work on all browsers which I tried.

As of the `</p>` tag, that is also weird because I definitely have an opening tag. Maybe `<form>` resets the paragraph automagically.

**Comment by bluegr** [comment] 2016-04-08 09:43
The validator's warning is correct. The <img> tag does include width and
height properties, but the <input> tag does not, even with the HTML 4.01
Transitional DTD that is used in the ScummVM website:
https://www.w3.org/TR/html4/sgml/loosedtd.html

To work around that issue, you could place these attributes in CSS instead:
<input type="image" src="/images/ppdonate.png
<http://www.scummvm.org/images/ppdonate.png>"
style="width:88px;height:35px;border:0
none" name="submit" alt="Support This Project">

The other warning about an invalid form inside a paragraph is also correct:
you can't include a block element (such as a form) inside a paragraph. You
could just wrap the paragraphs inside the form element to make this work
properly. For more info, check here:
http://stackoverflow.com/questions/1022041/why-doesnt-form-nested-in-p-validate-as-xhtml

Regards
Filippos



On Fri, Apr 8, 2016 at 12:01 PM, Eugene Sandulenko <notifications@github.com
> wrote:

> Yes, I saw that yesterday. Regarding the paypal link, this is really
> interesting, but the validator complains that in the following tag:
>
> <input type="image" src="/images/ppdonate.png" width="88" height="35"
> border="0" name="submit" alt="Support This Project">
>
> width, height and border attributes are not allowed. However, they work on
> all browsers which I tried.
>
> As of the </p> tag, that is also weird because I definitely have an
> opening tag. Maybe <form> resets the paragraph automagically.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scummvm/scummvm-web/issues/51#issuecomment-207335372>
>



-- 
"Experience is the name every one gives to their mistakes" - Oscar Wilde

**Comment by salty-horse** [comment] 2016-04-13 15:43
Fixed by 920ac17a405300c960ef4a5714622cbe739d68f4
(Forgot to mention in the commit message :( )

**Comment by salty-horse** [comment] 2016-04-13 16:10
Turns out I borked it a bit. I didn't preserve the top PayPal button's dimensions, which I fixed in 28b6006449f18d5a58b31ebb4859070544573be4.

Now the top PayPal button has some top padding in Chrome and Safari (not in Firefox)

**Comment by salty-horse** [comment] 2016-04-13 17:47
I fixed the padding issue. Please confirm, and I'll close this.

**Comment by sev-** [comment] 2016-04-13 19:48
Confirmed, closing, thanks a lot!

**Closed by sev-** 2016-04-13 19:48 UTC
